version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - manager

  app:
    build:
      context: ./
    ports:
      - 80:8080
    networks:
      - manager
    depends_on:
      - db

volumes:
  postgres:
    driver: local

networks:
  manager: